// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace KnightFrank.Blog.Tests.Regression.FeaturesCMS.Russia
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Knight Frank Russia Website")]
    public partial class KnightFrankRussiaWebsiteFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Knight.Frank.Russia.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Knight Frank Russia Website", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 4
#line 5
 testRunner.Given("user has visited Knight Frank Russia domain", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Russia Global Navigation is visible")]
        [NUnit.Framework.TestCaseAttribute("Страна:", null)]
        [NUnit.Framework.TestCaseAttribute("Language:", null)]
        [NUnit.Framework.TestCaseAttribute("Контакты", null)]
        [NUnit.Framework.TestCaseAttribute("Новости", null)]
        [NUnit.Framework.TestCaseAttribute("Карьера", null)]
        public virtual void RussiaGlobalNavigationIsVisible(string russiaGlobalNav, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Russia Global Navigation is visible", exampleTags);
#line 7
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line 8
 testRunner.Then(string.Format("user should see {0} site Global Navigation", russiaGlobalNav), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Russia Site Navigation is Visible")]
        [NUnit.Framework.TestCaseAttribute("Недвижимость", null)]
        [NUnit.Framework.TestCaseAttribute("Сотрудники", null)]
        [NUnit.Framework.TestCaseAttribute("Услуги", null)]
        [NUnit.Framework.TestCaseAttribute("Исследования", null)]
        [NUnit.Framework.TestCaseAttribute("Blog", null)]
        public virtual void RussiaSiteNavigationIsVisible(string russiaSiteNav, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Russia Site Navigation is Visible", exampleTags);
#line 19
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line 20
 testRunner.Then(string.Format("user should see {0} site navigation", russiaSiteNav), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Russia Search box tabs are visible")]
        [NUnit.Framework.TestCaseAttribute("Недвижимость в России", null)]
        [NUnit.Framework.TestCaseAttribute("Жилая в мире", null)]
        [NUnit.Framework.TestCaseAttribute("Коммерческая в мире", null)]
        [NUnit.Framework.TestCaseAttribute("Люди/Офисы", null)]
        [NUnit.Framework.TestCaseAttribute("Услуги", null)]
        [NUnit.Framework.TestCaseAttribute("Исследования", null)]
        public virtual void RussiaSearchBoxTabsAreVisible(string russiaSearchTabs, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Russia Search box tabs are visible", exampleTags);
#line 30
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line 31
 testRunner.Then(string.Format("user should see {0} search box tabs", russiaSearchTabs), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Russia Search tool placeholder text")]
        public virtual void RussiaSearchToolPlaceholderText()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Russia Search tool placeholder text", ((string[])(null)));
#line 42
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "searchWaterMark"});
            table1.AddRow(new string[] {
                        "Выберите регион или город, для поиска"});
#line 43
 testRunner.Then("user should see the russia search box text", ((string)(null)), table1, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
