// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace KnightFrank.Blog.Tests.Regression.FeaturesCMS
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Domain default languages")]
    public partial class DomainDefaultLanguagesFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Domain.Default.Language.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Domain default languages", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Knight Frank Homepage default languages")]
        public virtual void KnightFrankHomepageDefaultLanguages()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Knight Frank Homepage default languages", ((string[])(null)));
#line 4
this.ScenarioSetup(scenarioInfo);
#line 5
 testRunner.Given("user has visited the knight frank homepage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "website",
                        "Language"});
            table1.AddRow(new string[] {
                        "beta.knightfrank.co.uk",
                        ""});
            table1.AddRow(new string[] {
                        "beta.knightfrank.co.ke",
                        ""});
            table1.AddRow(new string[] {
                        "beta.knightfrank.mw",
                        ""});
            table1.AddRow(new string[] {
                        "beta.knightfrank.rw",
                        ""});
            table1.AddRow(new string[] {
                        "beta.knightfrank.co.za",
                        ""});
            table1.AddRow(new string[] {
                        "beta.knightfrank.co.tz",
                        ""});
            table1.AddRow(new string[] {
                        "beta.knightfrank.ug",
                        ""});
            table1.AddRow(new string[] {
                        "beta.knightfrank.co.zw",
                        ""});
            table1.AddRow(new string[] {
                        "beta.knightfrank.com.au",
                        ""});
            table1.AddRow(new string[] {
                        "beta.knightfrank.com.kh",
                        ""});
            table1.AddRow(new string[] {
                        "beta.knightfrank.com.cn",
                        "中文"});
            table1.AddRow(new string[] {
                        "beta.knightfrank.com.hk",
                        "English"});
            table1.AddRow(new string[] {
                        "beta.knightfrank.co.in",
                        ""});
            table1.AddRow(new string[] {
                        "beta.knightfrank.co.id",
                        ""});
            table1.AddRow(new string[] {
                        "beta.knightfrank.jp",
                        ""});
            table1.AddRow(new string[] {
                        "beta.knightfrank.com.my",
                        ""});
            table1.AddRow(new string[] {
                        "beta.knightfrank.co.nz",
                        ""});
            table1.AddRow(new string[] {
                        "beta.knightfrank.com.sg",
                        ""});
            table1.AddRow(new string[] {
                        "beta.knightfrank.kr",
                        ""});
            table1.AddRow(new string[] {
                        "beta.knightfrank.co.th",
                        "English"});
            table1.AddRow(new string[] {
                        "beta.knightfrank.com/austria",
                        "English"});
            table1.AddRow(new string[] {
                        "beta.knightfrank.be",
                        "English"});
            table1.AddRow(new string[] {
                        "beta.knightfrank.cz",
                        "Čeština"});
            table1.AddRow(new string[] {
                        "beta.knightfrank.fr",
                        "Français"});
            table1.AddRow(new string[] {
                        "beta.knightfrank.de",
                        "Deutsch"});
            table1.AddRow(new string[] {
                        "beta.knightfrank.ie",
                        ""});
            table1.AddRow(new string[] {
                        "beta.knightfrank.it",
                        "English"});
            table1.AddRow(new string[] {
                        "beta.knightfrank.com/monaco",
                        "English"});
            table1.AddRow(new string[] {
                        "beta.knightfrank.com/netherlands",
                        "English"});
            table1.AddRow(new string[] {
                        "beta.knightfrank.com.pl",
                        "Polski"});
            table1.AddRow(new string[] {
                        "beta.knightfrank.com/portugal",
                        "English"});
            table1.AddRow(new string[] {
                        "beta.knightfrank.com.ro",
                        ""});
            table1.AddRow(new string[] {
                        "beta.knightfrank.ru",
                        "русский"});
            table1.AddRow(new string[] {
                        "beta.knightfrank.es",
                        "Español"});
            table1.AddRow(new string[] {
                        "beta.knightfrank.com/switzerland",
                        "English"});
            table1.AddRow(new string[] {
                        "beta.knightfrank.ae",
                        ""});
            table1.AddRow(new string[] {
                        "beta.knightfrank.com.sa",
                        "العربية (الإمارات العربية المتحدة)"});
            table1.AddRow(new string[] {
                        "beta.knightfrank.us",
                        ""});
            table1.AddRow(new string[] {
                        "beta.knightfrank.com/caribbean",
                        "English"});
#line 6
 testRunner.Then("user has visited knight Frank \"sites\"", ((string)(null)), table1, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
