// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace KnightFrank.Blog.Tests.Regression.FeaturesCMS
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("OfficePageNew")]
    public partial class OfficePageNewFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "OfficePageNew.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "OfficePageNew", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 4
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "officePage"});
            table1.AddRow(new string[] {
                        "http://www.knightfrank.co.uk/contact/commercial-property-leeds"});
#line 5
 testRunner.Given("user has visited Leeds office page", ((string)(null)), table1, "Given ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("User should see global site navigation")]
        [NUnit.Framework.TestCaseAttribute("Country: UK", null)]
        [NUnit.Framework.TestCaseAttribute("About", null)]
        [NUnit.Framework.TestCaseAttribute("Careers", null)]
        [NUnit.Framework.TestCaseAttribute("Contact us", null)]
        [NUnit.Framework.TestCaseAttribute("My Knight Frank", null)]
        public virtual void UserShouldSeeGlobalSiteNavigation(string globalNav, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User should see global site navigation", exampleTags);
#line 9
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line 10
 testRunner.Then(string.Format("user should see {0} global navigation", globalNav), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("user should see the red my knight frank")]
        public virtual void UserShouldSeeTheRedMyKnightFrank()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("user should see the red my knight frank", ((string[])(null)));
#line 20
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "myKnightFrankRed"});
            table2.AddRow(new string[] {
                        "rgba(208, 16, 58, 1)"});
#line 21
 testRunner.Then("my knight frank on the global nav should be red", ((string)(null)), table2, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("User should see site navigation bar")]
        [NUnit.Framework.TestCaseAttribute("Properties", null)]
        [NUnit.Framework.TestCaseAttribute("People / Offices", null)]
        [NUnit.Framework.TestCaseAttribute("Services", null)]
        [NUnit.Framework.TestCaseAttribute("Research", null)]
        [NUnit.Framework.TestCaseAttribute("Blog", null)]
        public virtual void UserShouldSeeSiteNavigationBar(string siteNav, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User should see site navigation bar", exampleTags);
#line 27
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line 28
 testRunner.Then(string.Format("user should see {0} site nav", siteNav), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("user should see the site nav bar is green")]
        public virtual void UserShouldSeeTheSiteNavBarIsGreen()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("user should see the site nav bar is green", ((string[])(null)));
#line 38
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "siteNavGreen"});
            table3.AddRow(new string[] {
                        "rgba(1, 81, 81, 1)"});
#line 39
 testRunner.Then("user sees site nav bar is green", ((string)(null)), table3, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("User should see an image in the search area")]
        public virtual void UserShouldSeeAnImageInTheSearchArea()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User should see an image in the search area", ((string[])(null)));
#line 43
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "leedsImage"});
            table4.AddRow(new string[] {
                        "url(\"http://www.knightfrank.co.uk/resources/commercial/leeds-header-image.jpg\")"});
#line 44
 testRunner.Then("user should see the image in the search area", ((string)(null)), table4, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("User should see the search box tabs")]
        [NUnit.Framework.TestCaseAttribute("Residential", null)]
        [NUnit.Framework.TestCaseAttribute("Commercial", null)]
        [NUnit.Framework.TestCaseAttribute("People / Offices", null)]
        [NUnit.Framework.TestCaseAttribute("Services", null)]
        [NUnit.Framework.TestCaseAttribute("Research", null)]
        public virtual void UserShouldSeeTheSearchBoxTabs(string searchBoxTabs, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User should see the search box tabs", exampleTags);
#line 48
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line 49
 testRunner.Then(string.Format("user should see the {0} search box tab options", searchBoxTabs), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
